name: expire_check
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  get: ^4.7.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  intl: ^0.20.2
  google_fonts: ^6.3.0
  syncfusion_flutter_charts: ^30.2.4
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

# ✅ launcher icon config root level pe hoga
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/expire_check.png" # yaha apna logo ka path daalo
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
