// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVaJJX2irWdghNr1WnD1cCugHJzuRwtC4',
    appId: '1:283740870525:web:c8345e2842132b13465e14',
    messagingSenderId: '283740870525',
    projectId: 'expirecheck-40e67',
    authDomain: 'expirecheck-40e67.firebaseapp.com',
    storageBucket: 'expirecheck-40e67.firebasestorage.app',
    measurementId: 'G-MB5D7FWFY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9wlV7v3JuSe6eVNCfk8offErLB0gydHY',
    appId: '1:283740870525:android:482853bc657ce35b465e14',
    messagingSenderId: '283740870525',
    projectId: 'expirecheck-40e67',
    storageBucket: 'expirecheck-40e67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUc9Gq87fncRunVmXzRsXrMgTbFQCEwkU',
    appId: '1:283740870525:ios:1b00b4332cfc40d9465e14',
    messagingSenderId: '283740870525',
    projectId: 'expirecheck-40e67',
    storageBucket: 'expirecheck-40e67.firebasestorage.app',
    iosBundleId: 'com.example.expireCheck',
  );
}
